import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { FirstTheme } from "../themes/Theme";
import { App } from "@/templates/App";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} w-full h-full`}>
                <AppRouterCacheProvider
                    options={{
                        enableCssLayer: true,
                    }}
                >
                    <ThemeProvider theme={FirstTheme}>
                        <CssBaseline />
                        <App>{children}</App>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
