import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { FirstTheme } from "../themes/Theme";
import { App } from "@/templates/App";
import React from "react";
import { Providers } from "../lib/Redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <React.StrictMode>
            <html lang="en">
                <Providers>
                    <body className={`${inter.className}`}>
                        <AppRouterCacheProvider
                            options={{
                                enableCssLayer: true,
                            }}
                        >
                            <ThemeProvider theme={FirstTheme}>
                                <CssBaseline />
                                <App>{children}</App>
                            </ThemeProvider>
                        </AppRouterCacheProvider>
                    </body>
                </Providers>
            </html>
        </React.StrictMode>
    );
}
